version: "3"
services:
  video-toolkit:
    build:
      context: .
      dockerfile: Dockerfile 
      args:
        JOBS: ${JOBS}
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - .:/root
